name: CI

on:
  push:
    branches: [ main, feat/ml-app-core ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          black --check src app api tests
          isort --check-only src app api tests
          flake8 src app api tests
      - name: Run tests
        run: pytest -q
